services:
  db:
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_USER=l0_auth_service
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=l0_auth
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
      - "./database:/docker-entrypoint-initdb.d"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U l0_auth_service -d l0_auth"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data: