version: '3'

services:
  # Auth service
  auth:
    image: joseluisq/static-web-server:2.14.1
    # TODO: add file path
    
  # REST API service
  api:
    build:
      context: .
      dockerfile: dev.dockerfile
      target: development
      args:
        - JAR_FILE=target/*.jar
    environment: [] 
    ports:
      - 8000:8000
      - 10502:10502
    volumes:
      - ./:/app
    depends_on:
      db:
        condition: service_healthy

  # Postgres database
  db:
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
      - "./database:/docker-entrypoint-initdb.d"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # S3-compat object storage
  storage:
    image: minio/minio

  # CloudFlare worker (handle file uploads at the edge)
  worker-upload:
    build:
      context: worker/
      args: []
    environment: {}

volumes:
  db-data:
