name = "l0-storage-upload"
main = "src/index.js"
account_id = "5c5263e05bb1e54242b1afb12a5c9259"

routes = [
    { pattern = "storage.l0.mytiki.com/api/latest/upload", zone_id = "7be31970110fa56b1f8e1fe915a8b938" }
]

compatibility_date = "2022-09-12"

[vars]
PUBKEY = '{ "kty": "EC", "use": "sig", "crv": "P-256", "kid": "4570d35d-c0f6-44ff-a40b-350264bb6e2f", "x": "xgAA9ptVg940RBe8_nPmdzYrwUuU2gIeCaRe2v6uVL8", "y": "leiAoSoJvGSUjRIL5WvL9GIYV6YJ_VzbrP8838Y0h7M" }'
MAX_BYTES = 1000000

# The necessary secrets are:
# - REMOTE_ID
# - REMOTE_SECRET
# - WASABI_ID
# - WASABI_SECRET

# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these