name = "l0-storage-upload"
main = "src/index.js"
account_id = "5c5263e05bb1e54242b1afb12a5c9259"

routes = [
    { pattern = "storage.l0.mytiki.com/api/latest/upload", zone_id = "7be31970110fa56b1f8e1fe915a8b938" }
]

compatibility_date = "2022-09-12"

[vars]
# The necessary secrets are:
# - REMOTE_ID
# - REMOTE_SECRET
# - BUCKET_NAME
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these